artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/AnkitSangode/JavaScriptMiniProjects/raw/refs/heads/main/data_imdb.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  datadata_file: artifacts/data_ingestion/data_imdb.csv
  status_file: artifacts/data_validation/status.txt
  required_columns:
    - review
    - sentiment

data_transformation:
  root_dir: artifacts/data_transformation
  transformed_data_file: artifacts/data_transformation/cleaned_data.csv
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  vectorizer_file: artifacts/data_transformation/vectorizer.pkl