artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/AnkitSangode/JavaScriptMiniProjects/raw/refs/heads/main/data_imdb.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  datadata_file: artifacts/data_ingestion/data_imdb.csv
  status_file: artifacts/data_validation/status.txt
  required_columns:
    - review
    - sentiment